"""README generator for the AI Image Generation API Directory.

Generates a comprehensive README.md from provider data and scan results,
including provider tables, quick-start guides, and status badges.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from providers import Provider, Tier, PROVIDERS, get_providers
from scanner import ScanResult
from __version__ import __version__

# ---------------------------------------------------------------------------
# Status emoji mapping
# ---------------------------------------------------------------------------

STATUS_EMOJI = {
    "working": "\u2705",
    "reachable": "\U0001f7e1",
    "auth_missing": "\U0001f511",
    "auth_failed": "\U0001f534",
    "needs_credits": "\U0001f4b3",
    "rate_limited": "\u23f3",
    "timeout": "\u23f1\ufe0f",
    "error": "\u274c",
    "offline": "\U0001f4a4",
    "skipped": "\u23ed\ufe0f",
    "unknown": "\u2753",
}

# Friendly tier labels
TIER_LABELS = {
    Tier.free: "Tier 1 \u2013 Truly Free",
    Tier.generous_free: "Tier 2 \u2013 Generous Free Tier",
    Tier.free_credits: "Tier 3 \u2013 Free Credits on Signup",
    Tier.freemium: "Tier 4 \u2013 Freemium",
    Tier.payg: "Tier 5 \u2013 Pay-per-Use",
    Tier.router: "Routers / Aggregators",
    Tier.local: "Local / Self-Hosted",
}

TIER_ORDER = [
    Tier.free,
    Tier.generous_free,
    Tier.free_credits,
    Tier.freemium,
    Tier.payg,
    Tier.router,
    Tier.local,
]

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_report(
    scan_results: list[ScanResult] | None = None,
    output_file: str = "README.md",
) -> str:
    """Generate a full README.md and write it to *output_file*.

    Parameters
    ----------
    scan_results:
        Optional list of :class:`ScanResult` objects from the most recent
        provider scan.  When provided the README will include live status
        indicators next to each provider.
    output_file:
        Destination path for the generated file (default ``README.md``).

    Returns
    -------
    str
        The generated markdown text.
    """
    # Index scan results by provider name for O(1) lookups
    results_map: dict[str, ScanResult] = {}
    if scan_results:
        for r in scan_results:
            results_map[r.provider_name] = r

    providers = get_providers()

    sections: list[str] = [
        _generate_header(),
        _generate_toc(),
        _generate_why_section(),
        _generate_quick_start(),
        _generate_curl_examples(),
        _generate_provider_overview(providers, results_map),
    ]

    # Per-tier detailed sections
    for tier in TIER_ORDER:
        tier_providers = [p for p in providers if p.tier == tier]
        if tier_providers:
            sections.append(
                _generate_tier_section(tier, tier_providers, results_map)
            )

    sections.extend([
        _generate_status_legend(),
        _generate_project_structure(),
        _generate_setup(),
        _generate_cli_reference(),
        _generate_cross_link(),
        _generate_license(),
        _generate_credits(),
    ])

    readme = "\n\n".join(sections) + "\n"

    Path(output_file).write_text(readme, encoding="utf-8")
    return readme


# ---------------------------------------------------------------------------
# Section generators
# ---------------------------------------------------------------------------


def _generate_header() -> str:
    """Title, version badge, and key metric badges."""
    providers = get_providers()
    total = len(providers)
    free_count = len([p for p in providers if p.tier in (Tier.free, Tier.generous_free)])

    lines = [
        "<!-- AUTO-GENERATED by report_generator.py \u2013 do not edit manually -->",
        "",
        "# \U0001f3a8 AI Image Generation API Directory",
        "",
        (
            f"![Version](https://img.shields.io/badge/version-{__version__}-blue) "
            f"![Providers](https://img.shields.io/badge/providers-{total}-green) "
            f"![Free](https://img.shields.io/badge/free-{free_count}-brightgreen)"
        ),
        "",
        "> **The most comprehensive directory of free & affordable AI image generation APIs**",
    ]
    return "\n".join(lines)


def _generate_toc() -> str:
    """Collapsible table of contents."""
    toc_items = [
        ("Why This Exists", "#-why-this-exists"),
        ("Quick Start (Python)", "#-quick-start-python"),
        ("Quick Start (cURL)", "#-quick-start-curl"),
        ("Provider Overview", "#-provider-overview"),
    ]
    for tier in TIER_ORDER:
        label = TIER_LABELS[tier]
        anchor = "#-" + label.lower().replace(" ", "-").replace("/", "").replace("\u2013", "").replace("--", "-").strip("-")
        toc_items.append((label, anchor))

    toc_items.extend([
        ("Status Legend", "#-status-legend"),
        ("Project Structure", "#-project-structure"),
        ("Setup", "#-setup"),
        ("CLI Reference", "#-cli-reference"),
        ("Sister Project \u2013 LLM APIs", "#-sister-project--llm-apis"),
        ("License", "#-license"),
        ("Credits", "#-credits"),
    ])

    lines = [
        "<details>",
        "<summary><strong>Table of Contents</strong></summary>",
        "",
    ]
    for title, anchor in toc_items:
        lines.append(f"- [{title}]({anchor})")
    lines.append("")
    lines.append("</details>")
    return "\n".join(lines)


def _generate_why_section() -> str:
    """Brief explanation of the project's purpose."""
    return "\n".join([
        "## \U0001f4a1 Why This Exists",
        "",
        "Finding free or affordable AI image generation APIs shouldn\u2019t be hard.",
        "Most lists are out of date within weeks and never tell you whether an",
        "endpoint is actually *working*.",
        "",
        "This directory is **auto-scanned** \u2013 a CI job hits every endpoint on a",
        "schedule, records response times, and updates this README so you always",
        "know which APIs are live right now.",
    ])


def _generate_quick_start() -> str:
    """Python quick-start example using the OpenAI SDK with HuggingFace."""
    return "\n".join([
        "## \U0001f680 Quick Start (Python)",
        "",
        "Most providers expose an OpenAI-compatible `/v1/images/generations`",
        "endpoint, so you can use the official OpenAI SDK with a custom",
        "`base_url`.",
        "",
        "```python",
        "from openai import OpenAI",
        "",
        "# Example: HuggingFace Inference API (free, token recommended)",
        "client = OpenAI(",
        '    base_url="https://api-inference.huggingface.co/v1/",',
        '    api_key="hf_YOUR_TOKEN",  # or set HUGGINGFACE_API_KEY env var',
        ")",
        "",
        "response = client.images.generate(",
        '    model="black-forest-labs/FLUX.1-schnell",',
        '    prompt="A futuristic cityscape at sunset, cyberpunk style",',
        '    size="1024x1024",',
        "    n=1,",
        ")",
        "",
        "image_url = response.data[0].url",
        'print("Generated:", image_url)',
        "```",
    ])


def _generate_curl_examples() -> str:
    """cURL quick-start example."""
    return "\n".join([
        "## \U0001f4e1 Quick Start (cURL)",
        "",
        "```bash",
        "# Pollinations \u2013 completely free, no key needed",
        "curl -s 'https://image.pollinations.ai/prompt/"
        "A%20red%20panda%20wearing%20a%20top%20hat' -o panda.jpg",
        "",
        "# HuggingFace Inference API",
        'curl -X POST "https://api-inference.huggingface.co/models/'
        'black-forest-labs/FLUX.1-schnell" \\',
        '  -H "Authorization: Bearer $HUGGINGFACE_API_KEY" \\',
        '  -H "Content-Type: application/json" \\',
        '  -d \'{"inputs": "A magical forest with glowing mushrooms"}\' \\',
        "  -o forest.png",
        "```",
    ])


def _generate_provider_overview(
    providers: list[Provider],
    results: dict[str, ScanResult],
) -> str:
    """Summary table of all providers with optional live status."""
    lines = [
        "## \U0001f5c2\ufe0f Provider Overview",
        "",
    ]

    # Build header
    has_status = bool(results)
    header_cols = ["Provider", "Tier", "Free Limits"]
    if has_status:
        header_cols.append("Status")
    sep_cols = ["---", "---", "---"]
    if has_status:
        sep_cols.append(":---:")

    lines.append("| " + " | ".join(header_cols) + " |")
    lines.append("| " + " | ".join(sep_cols) + " |")

    for p in providers:
        tier_label = TIER_LABELS.get(p.tier, str(p.tier))
        free_limits = p.free_limits or "\u2014"
        row = [f"**{p.name}**", tier_label, free_limits]
        if has_status:
            sr = results.get(p.name)
            if sr:
                emoji = STATUS_EMOJI.get(sr.status, STATUS_EMOJI["unknown"])
                row.append(f"{emoji} {sr.status}")
            else:
                row.append(STATUS_EMOJI["skipped"] + " skipped")
        lines.append("| " + " | ".join(row) + " |")

    return "\n".join(lines)


def _generate_tier_section(
    tier: Tier,
    providers: list[Provider],
    results: dict[str, ScanResult],
) -> str:
    """Detailed table for a single tier."""
    label = TIER_LABELS.get(tier, str(tier))
    lines = [
        f"## \U0001f3af {label}",
        "",
    ]

    has_status = bool(results)
    header_cols = ["Provider", "Endpoint", "Free Limits", "Models", "Capabilities"]
    if has_status:
        header_cols.append("Status")
    sep_cols = ["---", "---", "---", "---", "---"]
    if has_status:
        sep_cols.append(":---:")

    lines.append("| " + " | ".join(header_cols) + " |")
    lines.append("| " + " | ".join(sep_cols) + " |")

    for p in providers:
        name_cell = f"[{p.name}]({p.signup_url})" if p.signup_url else p.name
        endpoint = f"`{p.endpoint}`" if p.endpoint else "\u2014"
        free_limits = p.free_limits or "\u2014"
        models = ", ".join(p.models[:3]) if p.models else "\u2014"
        if p.models and len(p.models) > 3:
            models += f" +{len(p.models) - 3} more"
        capabilities = ", ".join(p.capabilities) if p.capabilities else "txt2img"

        row = [name_cell, endpoint, free_limits, models, capabilities]

        if has_status:
            sr = results.get(p.name)
            if sr:
                emoji = STATUS_EMOJI.get(sr.status, STATUS_EMOJI["unknown"])
                latency_str = ""
                if sr.latency_ms is not None:
                    latency_str = f" ({sr.latency_ms:.0f}ms)"
                row.append(f"{emoji}{latency_str}")
            else:
                row.append(STATUS_EMOJI["skipped"])

        lines.append("| " + " | ".join(row) + " |")

    return "\n".join(lines)


def _generate_status_legend() -> str:
    """Explain what each status value means."""
    lines = [
        "## \U0001f6a6 Status Legend",
        "",
        "| Symbol | Status | Meaning |",
        "| :---: | --- | --- |",
    ]
    descriptions = {
        "working": "Endpoint returned a valid image",
        "reachable": "Endpoint responded but image was not verified",
        "auth_missing": "API key required but not configured",
        "auth_failed": "API key was rejected by the provider",
        "needs_credits": "Account has no remaining credits",
        "rate_limited": "Too many requests \u2013 try again later",
        "timeout": "Request timed out",
        "error": "Endpoint returned an error",
        "offline": "Endpoint is unreachable",
        "skipped": "Provider was not scanned",
        "unknown": "Status could not be determined",
    }
    for status, emoji in STATUS_EMOJI.items():
        desc = descriptions.get(status, "")
        lines.append(f"| {emoji} | `{status}` | {desc} |")

    return "\n".join(lines)


def _generate_project_structure() -> str:
    """Directory tree of the project."""
    return "\n".join([
        "## \U0001f4c1 Project Structure",
        "",
        "```text",
        "ai_image_generation/",
        "\u251c\u2500\u2500 __version__.py          # Version string",
        "\u251c\u2500\u2500 config.py               # Configuration loader",
        "\u251c\u2500\u2500 config.yaml             # Default configuration",
        "\u251c\u2500\u2500 providers.py            # Provider dataclass & registry",
        "\u251c\u2500\u2500 scanner.py              # Endpoint health scanner",
        "\u251c\u2500\u2500 report_generator.py     # This file \u2013 README generator",
        "\u251c\u2500\u2500 requirements.txt        # Python dependencies",
        "\u251c\u2500\u2500 .env.example            # API key template",
        "\u251c\u2500\u2500 data/                   # Scan results & caches",
        "\u251c\u2500\u2500 adapters/               # Per-provider HTTP adapters",
        "\u251c\u2500\u2500 agents/                 # AI-powered discovery agents",
        "\u251c\u2500\u2500 discovery/              # Provider discovery strategies",
        "\u251c\u2500\u2500 plugins/                # Optional plugins (benchmark, export, \u2026)",
        "\u251c\u2500\u2500 recipes/                # End-to-end usage recipes",
        "\u251c\u2500\u2500 search/                 # Web search integration",
        "\u251c\u2500\u2500 tools/                  # CLI entry points",
        "\u2514\u2500\u2500 examples/               # Standalone example scripts",
        "```",
    ])


def _generate_setup() -> str:
    """Installation and environment setup instructions."""
    return "\n".join([
        "## \u2699\ufe0f Setup",
        "",
        "### 1. Install dependencies",
        "",
        "```bash",
        "pip install -r requirements.txt",
        "```",
        "",
        "### 2. Configure API keys",
        "",
        "```bash",
        "cp .env.example .env",
        "# Edit .env and add keys for the providers you want to test.",
        "# Providers marked \u201cno key\u201d (e.g. Pollinations) work without any setup.",
        "```",
        "",
        "### 3. (Optional) Customise settings",
        "",
        "Edit `config.yaml` to change scan concurrency, timeouts, discovery",
        "strategies, and more.  Environment variables override YAML values \u2013",
        "see `config.py` for the full mapping.",
    ])


def _generate_cli_reference() -> str:
    """List of CLI commands."""
    return "\n".join([
        "## \U0001f4bb CLI Reference",
        "",
        "| Command | Description |",
        "| --- | --- |",
        "| `python -m tools.scan` | Scan all providers and save results |",
        "| `python -m tools.scan --tier 1` | Scan only Tier 1 (free) providers |",
        "| `python -m report_generator` | Regenerate this README from latest data |",
        "| `python -m discovery` | Run AI-powered provider discovery |",
        "| `python -m plugins.benchmark` | Benchmark image quality & latency |",
        "| `python -m plugins.export --format csv` | Export provider data to CSV/JSON |",
        "| `python -m tools.proxy` | Start the local OpenAI-compatible proxy |",
    ])


def _generate_cross_link() -> str:
    """Cross-link to the LLM sister repository."""
    return "\n".join([
        "## \U0001f517 Sister Project \u2013 LLM APIs",
        "",
        "Looking for **text / chat / completion** APIs instead?  Check out the",
        "companion directory:",
        "",
        "> **[AI LLM API Directory](https://github.com/TaylorAmarelTech/ai_llm_api_directory)**",
        "> \u2013 The same idea, but for Large Language Model endpoints (GPT, Claude,",
        "> Llama, Mixtral, and more).",
    ])


def _generate_license() -> str:
    """MIT licence section."""
    return "\n".join([
        "## \U0001f4dc License",
        "",
        "This project is licensed under the **MIT License** \u2013 see the",
        "[LICENSE](LICENSE) file for details.",
    ])


def _generate_credits() -> str:
    """Credits section."""
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return "\n".join([
        "## \U0001f64f Credits",
        "",
        f"Built and maintained by **[TaylorAmarelTech](https://github.com/TaylorAmarelTech)**.",
        "",
        f"Last generated: {now_str}",
    ])


# ---------------------------------------------------------------------------
# Allow running as a standalone script:  python -m report_generator
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    output = generate_report()
    print(f"README.md generated ({len(output):,} chars)")
